### ISSUE TITLE
Crashing Ardour

### ISSUE THREAD

**Issue by lrfinotti** [x42/zconvo.lv2#1]
It seems that version 0.4.2 still crashes Ardour.  See the [crash log](https://github.com/x42/zconvo.lv2/files/6336192/gdb7.txt).  

Removing all instances resolved the issue and I haven't had a crash since.

Let me know if I can provide any more info.

**Comment by x42** [comment]
"SIGFPE, Arithmetic exception" -- that is mysterious. Does it happen reliably with a given session or IR?

Could you try this with a debug build of the plugin:

```
## sudo apt-get build-dep x42-plugins

make clean
make OPTIMIZATIONS="-O3 -g -ffast-math -fno-finite-math-only" STRIP=/bin/true
rm -rf ~/.lv2/zeroconvo.lv2/
cp -a build   ~/.lv2/zeroconvo.lv2
```

**Comment by lrfinotti** [comment]
Thanks for the reply.

The session was crashing randomly, but consistently.  I could not go 15 minutes without a crash.  Sometimes early, sometimes taking a little longer.  After I first upgraded to the newer version, though, I played with it for a while with no crashes.  The next day I was having the crashes consistently.

The IRs I was using were all from M7.  They were "Rooms - Studio A", "Halls - Concert Hall", and some plate I don't recall.

I will try it again tonight or tomorrow morning, but I wanted to clarify your instructions.  I currently have x42-plugins from KXStudio (5:20210114-1kxstudio1), and I installed zconvo from the tarball.  Will apt be able to get the correct source?

**Comment by x42** [comment]
>  Will apt be able to get the correct source?

No. debug version are require building from source:

```
sudo apt-get build-dep x42-plugins
git clone git://github.com/x42/zconvo.lv2.git
cd zconvo.lv2
make OPTIMIZATIONS="-O3 -g -ffast-math -fno-finite-math-only" STRIP=/bin/true
rm -rf ~/.lv2/zeroconvo.lv2/
cp -a build   ~/.lv2/zeroconvo.lv2
```

If you're not comfortable with doing that, I can create a debug build.  Linux? 64bit Intel?

PS. You do **not** have to un-install the kxstudio package. Ardour will automatically pick the newer version from `~/.lv2`

**Comment by lrfinotti** [comment]
Thanks again!  I think I have it all set up now.  (I thought I was missing some git commands to get the source.)

I will test tonight or tomorrow morning.

**Comment by lrfinotti** [comment]
FYI: I added the plugins back to the session and worked on it for over an hour today with no crashes...  I will keep working on it and post a log if it crashes again.

**Comment by lrfinotti** [comment]
I've used the session extensively after these crashes with no more problems...  So I suppose that this can be closed now.  (I will leave it to you, just in case.)  Thanks for your help and sorry for the noise...
