### ISSUE TITLE
How do I load an IR?

### ISSUE THREAD

**Issue by LiveNathan** [x42/zconvo.lv2#4]
Hi, I have the IR in the folder, but after opening the plugin, I don't see any option to load it.
![2022-10-12 at 16 35 32@2x](https://user-images.githubusercontent.com/60303904/195452407-ff4a7f05-f770-41b2-bb0e-4bee952a65ca.png)
![2022-10-12 at 16 36 34@2x](https://user-images.githubusercontent.com/60303904/195452539-8c1e658a-7b04-4fe2-9181-9ae348dcf9a5.png)

**Comment by x42** [comment]
It is a missing feature in Reaper. see also https://forum.cockos.com/showthread.php?t=268867
the LV2 plugin expects the host to provide a file-chooser dialog, but Reaper's LV2 implementation does not offer this [yet].

**Comment by x42** [comment]
Meanwhile perhaps try to load the plugin inside Carla -- or use the preset-only variant

**Comment by falkTX** [comment]
Using https://github.com/DISTRHO/Ildaeil is also an option.
When loading zconvo it will show an "open file..." button
There was a little bug with this and the new v1.2 will be needed (to be released tomorrow, or use early builds from github actions)

![image](https://user-images.githubusercontent.com/1334853/195846051-9c4047a9-40e2-4729-a7bd-fb826ce1bf37.png)

**Comment by LiveNathan** [comment]
Thanks so much. I’ll try that.
Carla was the first thing i tried. Never could get it to load.

Nathan Lively
(512) 538-8289
sounddesignlive.com

**Comment by falkTX** [comment]
I just tagged v1.2 btw, binaries will start to appear soon, around 1h maximum.
https://github.com/DISTRHO/Ildaeil/releases/tag/v1.2
