### ISSUE TITLE
Silence when loading custom IRs

### ISSUE THREAD

**Issue by fritzbauer** [x42/zconvo.lv2#6]
**Issue**
When using the zeroconf plugins with a custom IR file, I do not get any sound.
This was initially observed in Carla and just now replicated in Ardour.
It does not work, regardless whether Buffered convolution is enabled or disabled. It also does not work when loading the default delta-48k.wav IR file.

**What is working**
* The versions with presets are working in Carla as well as in Ardour
* When increasing up the "Dry" parameter, I start receiving output, but of course that's only the dry output.
* I usually used convoLV2 in the past, however since this commit, it is not longer installed with the x42 plugins: https://github.com/x42/x42-plugins/commit/c3e9890a65e423ac70d576fa03f8ca8493ba1f35

**Troubleshooting**
* Probably you can replicate it as well?
* If not, I am available to help troubleshooting the issue. Please give me a starting point, what might be good to check first. I could not find any logs so far.

**System information**
* Archlinux on latest updates
* Pipewire
* Gnome
* Kernel 6.3.5
* Plugin version: x42-plugins 20230512-1

Thank you very much for the help!

**Comment by fritzbauer** [comment]
Amazing! Thank you so much for the quick help! Fix confirmed working :)

**Comment by myrrc** [comment]
I can also experience that in Reaper:

OS: Debian 13 Trixie
Reaper v7.14
zconvolv version 0.7.1

The non-preset versions also work fine
